'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Modulo_Ventas.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _1486485553_ago_arrow_arrow_left_back_previous_direction_left_81160() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("1486485553-ago-arrow-arrow-left-back-previous-direction-left_81160", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _1486564180_finance_financial_report_81493() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("1486564180-finance-financial-report_81493", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _1491253410_6document_report_82881() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("1491253410-6document-report_82881", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _2499346() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("2499346", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _3d_applications_folder_20538() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("3d_applications_folder_20538", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _40_104848() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("40_104848", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property abrir() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abrir", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property agregar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("agregar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property arrow_refresh_15732() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_refresh_15732", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property arrow_refresh_15732_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_refresh_15732(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property arrow_refresh_157321() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_refresh_157321", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property arrow_refresh_157322() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_refresh_157322", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property atras() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("atras", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ATRASSS() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ATRASSS", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property backward_icon_125062() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("backward_icon_125062", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barchart2_77998() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barchart2_77998", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property bindersbluedocuments_carpetas_azu_10985() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bindersbluedocuments_carpetas_azu_10985", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property buscar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property buscar_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property buscar2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buscar2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property calidad() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("calidad", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property can_a() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("can-a", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property can_a1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("can-a1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property can_abi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("can-abi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property can_cer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("can_cer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Cargo_1_35517() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cargo_1_35517", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cerrar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cerrar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cerrar2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cerrar2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cerrar21() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cerrar21", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property check_icon_icons_com_73639() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("check_icon-icons.com_73639", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property close() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property close222() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("close222", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property diagram_14_24503() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("diagram-14_24503", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property diseñoy_textura() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("diseñoy textura", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property diskette_save_saveas_1514() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("diskette_save_saveas_1514", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property document_delete_256_icon_icons_com_75995() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("document_delete_256_icon-icons.com_75995", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property document_delete_256_icon_icons1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("document_delete_256_icon-icons1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property DocumentEdit_40924() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("DocumentEdit_40924", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property editar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("editar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property editar2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("editar2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property eidviewer_94042() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("eidviewer_94042", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property EXCEL_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("EXCEL}", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property excel_18897() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("excel_18897", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property excel_18897_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("excel_18897(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property EXCELL() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("EXCELL", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property EXCELL2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("EXCELL2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property file_delete_remove_13907() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("file_delete_remove_13907", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property file_pdf_download_icon_icons_com_68954_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("file_pdf_download_icon-icons.com_68954(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property forklift_truck_transport_warehouse_icon_148904() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forklift_truck_transport_warehouse_icon_148904", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property grafica() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("grafica", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GRAFICO2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GRAFICO2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property guardar2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("guardar2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property guardar22() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("guardar22", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property iconfinder_digital_coin_4341275_120581() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("iconfinder-digital-coin-4341275_120581", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property iconfinder_infographic_management_4341272_120578() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("iconfinder-infographic-management-4341272_120578", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property iconfinder_mail_management_4341274_120573() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("iconfinder-mail-management-4341274_120573", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property if_12_harry_potter_colour_harrys_lightning_scar_2730325_88172() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("if-12-harry-potter-colour-harrys-lightning-scar-2730325_88172", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property if_12_harry_potter_colour_harrys_lightning_scar_2730325_88172_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("if-12-harry-potter-colour-harrys-lightning-scar-2730325_88172(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property imprimir() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imprimir", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property imprimir2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imprimir2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property LOGO_DG_PNG() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("LOGO DG PNG", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property LOGO_DG_PNG1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("LOGO DG PNG1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo_VIANNY() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo_VIANNY", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo_Vianny_fondo_índigo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo Vianny fondo índigo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logo_Vianny_sin_fondo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logo Vianny sin fondo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Logoblanco() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Logoblanco", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Lorry_Green_icon_icons_com_54887() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Lorry_Green_icon-icons.com_54887", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Lorry_Green_icon_icons_com_54887_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Lorry_Green_icon-icons.com_54887(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Maersk_4_35495() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Maersk_4_35495", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property microsoft_excel_22733() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("microsoft_excel_22733", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property new_add_insert_file_13948() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("new_add_insert_file_13948", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property new_add_insert_file_13948_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("new_add_insert_file_13948(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property new_page_document_16676() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("new_page_document_16676", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property note_task_comment_message_edit_write_108613() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("note-task-comment-message-edit-write_108613", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Ordering_25406() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ordering_25406", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property papeleras_reciclaje_005() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("papeleras-reciclaje-005", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property payment_tax_invoice_calculator_icon_188774() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("payment_tax_invoice_calculator_icon_188774", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Portada() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Portada", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property print_printer_printing_1549() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("print_printer_printing_1549", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property printer_icon_icons_com_53651() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("printer_icon-icons.com_53651", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property printer_icon_icons_com_53651_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("printer_icon-icons.com_53651(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ROLLO() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ROLLO", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ROLLO_opt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ROLLO_opt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ROLLOS2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ROLLOS2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property search_find_database_16703() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_find_database_16703", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property shoppaymentorderbuy_08_icon_icons_com_73885() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("shoppaymentorderbuy-08_icon-icons.com_73885", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property shopping_cart_market_ecommerce_shop_icon_181465() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("shopping_cart_market_ecommerce_shop_icon_181465", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property stock() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("stock", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property systemshutdown_103390() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("systemshutdown_103390", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property systemshutdown_103390_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("systemshutdown_103390(1)", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property tic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("tic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property update() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property VIANNY() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("VIANNY", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property warehouse_storage_unit_storehouse_icon_192428() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warehouse_storage_unit_storehouse_icon_192428", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Wood_Box_Closed_35527() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Wood-Box-Closed_35527", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
